// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaF39WzCtGsMA7B1dvVR2R14y8qTA7VGA',
    appId: '1:1005075412909:web:72e429d17e3856be079324',
    messagingSenderId: '1005075412909',
    projectId: 'spotify-flutter-bloc',
    authDomain: 'spotify-flutter-bloc.firebaseapp.com',
    storageBucket: 'spotify-flutter-bloc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9uzqjWqD-fkF4RobLqNF2xSzl7Y-rpTI',
    appId: '1:1005075412909:android:c01511a1740c1534079324',
    messagingSenderId: '1005075412909',
    projectId: 'spotify-flutter-bloc',
    storageBucket: 'spotify-flutter-bloc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHuQgcofVNdLSdECuH4px5gg-ADVvzh0Q',
    appId: '1:1005075412909:ios:1a761184f111651a079324',
    messagingSenderId: '1005075412909',
    projectId: 'spotify-flutter-bloc',
    storageBucket: 'spotify-flutter-bloc.appspot.com',
    iosBundleId: 'com.example.spotifyFlutterBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHuQgcofVNdLSdECuH4px5gg-ADVvzh0Q',
    appId: '1:1005075412909:ios:1a761184f111651a079324',
    messagingSenderId: '1005075412909',
    projectId: 'spotify-flutter-bloc',
    storageBucket: 'spotify-flutter-bloc.appspot.com',
    iosBundleId: 'com.example.spotifyFlutterBloc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaF39WzCtGsMA7B1dvVR2R14y8qTA7VGA',
    appId: '1:1005075412909:web:e5aa09bdd8e78874079324',
    messagingSenderId: '1005075412909',
    projectId: 'spotify-flutter-bloc',
    authDomain: 'spotify-flutter-bloc.firebaseapp.com',
    storageBucket: 'spotify-flutter-bloc.appspot.com',
  );
}
